<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { Bell, LogOut, MapPin, LockKeyhole, Moon, Sun } from '@lucide/vue'
import PageHeader from '@/components/PageHeader.vue'
import InlineNotice from '@/components/InlineNotice.vue'
import UserAvatar from '@/components/UserAvatar.vue'
import { api, unwrap } from '@/api/client'
import { useAuthStore } from '@/stores/auth'
import { useClientTheme } from '@/composables/useClientTheme'
import type { Address } from '@/types'

const auth=useAuthStore(),router=useRouter(),home=ref<any>(null),addresses=ref<Address[]>([]),notifications=ref<any[]>([]),showAddress=ref(false),showSettings=ref(false),message=ref(''),error=ref('')
const form=reactive({recipient_name:'',phone:auth.account?.phone||'',province:'',city:'',district:'',detail:'',is_default:true})
const profile=reactive({nickname:auth.account?.nickname||'',phone:auth.account?.phone||'',email:auth.account?.email||''})
const identifierForm=reactive({identifier:auth.account?.username||''})
const password=reactive({current_password:'',new_password:''})
const identifierSaving=ref(false),identifierMessage=ref(''),identifierError=ref('')
const {theme,setTheme}=useClientTheme()
const safeCount=(value:unknown)=>{const number=Number(value);return Number.isFinite(number)?number:0}
const repairCount=computed(()=>safeCount(home.value?.counts?.repairs))
const recycleCount=computed(()=>safeCount(home.value?.counts?.recycles))
const workItemCount=computed(()=>safeCount(home.value?.counts?.work_items ?? (repairCount.value+safeCount(home.value?.counts?.orders)+recycleCount.value)))
const unreadCount=computed(()=>safeCount(home.value?.counts?.unread_notifications))
const identifierRemaining=computed(()=>safeCount(home.value?.identifier_change?.remaining))
const normalizedIdentifier=computed(()=>identifierForm.identifier.trim().replace(/^@/,'').toLowerCase())
async function load(){[home.value,addresses.value,notifications.value]=await Promise.all([api.get('/me').then(r=>unwrap<any>(r)),api.get('/addresses').then(r=>unwrap<Address[]>(r)),api.get('/notifications').then(r=>unwrap<any[]>(r))]);identifierForm.identifier=home.value?.account?.username||auth.account?.username||''}
async function addAddress(){error.value='';try{await api.post('/addresses',form);showAddress.value=false;Object.assign(form,{recipient_name:'',province:'',city:'',district:'',detail:''});await load()}catch(e){error.value=e instanceof Error?e.message:'保存失败'}}
async function read(id:number){await api.post(`/notifications/${id}/read`);await load()}
async function saveProfile(){error.value='';message.value='';try{const data=unwrap<any>(await api.patch('/auth/profile',profile));auth.account={...auth.account!,...data};message.value='账户资料已更新'}catch(e){error.value=e instanceof Error?e.message:'保存失败'}}
async function saveIdentifier(){if(identifierSaving.value||identifierRemaining.value<=0||normalizedIdentifier.value===home.value?.account?.username)return;identifierSaving.value=true;identifierError.value='';identifierMessage.value='';try{const data=unwrap<any>(await api.patch('/auth/identifier',{identifier:identifierForm.identifier}));auth.account={...auth.account!,...data.account};home.value.account={...home.value.account,...data.account};home.value.identifier_change=data.identifier_change;identifierForm.identifier=data.account.username;identifierMessage.value=`识别码已更新为 ${data.account.identifier}，本年度剩余 ${data.identifier_change.remaining} 次`}catch(e){identifierError.value=e instanceof Error?e.message:'识别码修改失败'}finally{identifierSaving.value=false}}
async function changePassword(){error.value='';message.value='';try{await api.post('/auth/change-password',password);password.current_password='';password.new_password='';message.value='密码已更新，其他设备登录已失效'}catch(e){error.value=e instanceof Error?e.message:'修改失败'}}
async function avatar(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;const body=new FormData();body.append('file',file);const data=unwrap<{avatar_url:string}>(await api.post('/me/avatar',body));if(auth.account)auth.account={...auth.account,avatar_url:data.avatar_url};await load()}
async function logout(){await auth.logout();await router.replace('/auth')}
onMounted(load)
</script>

<template>
  <PageHeader title="我的" subtitle="账号、业务记录和消息"/>
  <section v-if="home" class="content-card profile-identity"><UserAvatar :src="home.account.avatar_url" :name="home.account.nickname" :size="58"/><div><h2>{{home.account.nickname}}</h2><p class="profile-identifier">{{home.account.identifier || `@${home.account.username}`}}</p><p class="muted">{{home.account.phone}}<template v-if="home.account.email"> · {{home.account.email}}</template></p></div></section>
  <section v-if="home" class="card-grid section"><article class="service-card"><strong style="font-size:28px">{{workItemCount}}</strong><p>订单与工单</p></article><article class="service-card"><strong style="font-size:28px">{{repairCount}}</strong><p>维修记录</p></article><article class="service-card"><strong style="font-size:28px">{{recycleCount}}</strong><p>回收申请</p></article><article class="service-card"><strong style="font-size:28px">{{unreadCount}}</strong><p>未读消息</p></article></section>
  <section class="section"><div class="section-heading"><h2><MapPin :size="19" style="vertical-align:-3px"/> 收货地址</h2><button class="button secondary" @click="showAddress=!showAddress">新增地址</button></div><form v-if="showAddress" class="form-card form-grid" @submit.prevent="addAddress"><div class="form-grid two"><div class="field"><label>收件人</label><input v-model="form.recipient_name" required/></div><div class="field"><label>手机号</label><input v-model="form.phone" required/></div><div class="field"><label>省份</label><input v-model="form.province" required/></div><div class="field"><label>城市</label><input v-model="form.city" required/></div></div><div class="field"><label>详细地址</label><input v-model="form.detail" required/></div><InlineNotice :message="error" type="error"/><button class="button">保存地址</button></form><div class="list"><article v-for="item in addresses" :key="item.id" class="list-item"><MapPin/><div class="list-item-main"><h3>{{item.recipient_name}} · {{item.phone}}</h3><p>{{item.province}}{{item.city}}{{item.district}}{{item.detail}}</p></div><span v-if="item.is_default" class="pill">默认</span></article></div></section>
  <section class="section"><div class="section-heading"><h2><Bell :size="19" style="vertical-align:-3px"/> 消息中心</h2></div><div class="list"><button v-for="item in notifications" :key="item.id" class="list-item" @click="read(item.id)"><div class="list-item-main" style="text-align:left"><h3>{{item.title}}</h3><p>{{item.content}}</p></div><span v-if="!item.is_read" class="pill blue">未读</span></button><div v-if="!notifications.length" class="empty-state">暂无消息。</div></div></section>
  <section class="section"><div class="button-row"><button class="button secondary" @click="showSettings=!showSettings"><LockKeyhole :size="18"/>设置</button><button class="button danger" @click="logout"><LogOut :size="18"/>退出登录</button></div><div v-if="showSettings" class="form-card form-grid settings-panel" style="margin-top:12px"><h2>外观</h2><div class="theme-setting" role="group" aria-label="客户端外观模式"><div><strong>深浅色模式</strong><p class="muted">选择后会保存在这台设备上。</p></div><div class="theme-options"><button type="button" :class="{active:theme==='light'}" :aria-pressed="theme==='light'" @click="setTheme('light')"><Sun :size="18"/>浅色</button><button type="button" :class="{active:theme==='dark'}" :aria-pressed="theme==='dark'" @click="setTheme('dark')"><Moon :size="18"/>深色</button></div></div><hr style="width:100%;border:0;border-top:1px solid var(--line)"/><h2>账号资料</h2><section class="identifier-settings"><div class="identifier-settings-head"><div><strong>识别码</strong><p class="muted">每个自然年最多修改 2 次，修改后请使用新识别码登录。</p></div><span class="pill blue">本年度剩余 {{identifierRemaining}} 次</span></div><div class="identifier-change-row"><div class="identifier-input"><span>@</span><input v-model="identifierForm.identifier" autocomplete="username" minlength="3" maxlength="81" aria-label="新识别码" :disabled="identifierRemaining<=0"/></div><button type="button" class="button secondary" :disabled="identifierSaving||identifierRemaining<=0||normalizedIdentifier===home?.account?.username" @click="saveIdentifier">{{identifierSaving?'正在修改…':'修改识别码'}}</button></div><InlineNotice :message="identifierMessage" type="success"/><InlineNotice :message="identifierError" type="error"/></section><hr style="width:100%;border:0;border-top:1px solid var(--line)"/><div class="field"><label>头像</label><input type="file" accept="image/jpeg,image/png,image/webp" @change="avatar"/></div><div class="form-grid two"><div class="field"><label>昵称</label><input v-model="profile.nickname"/></div><div class="field"><label>手机号</label><input v-model="profile.phone"/></div></div><div class="field"><label>邮箱</label><input v-model="profile.email" type="email"/></div><button class="button" @click="saveProfile">保存资料</button><hr style="width:100%;border:0;border-top:1px solid var(--line)"/><h2>密码安全</h2><div class="field"><label>当前密码</label><input v-model="password.current_password" type="password"/></div><div class="field"><label>新密码</label><input v-model="password.new_password" type="password" minlength="8"/></div><button class="button secondary" @click="changePassword">修改密码</button><InlineNotice :message="message" type="success"/><InlineNotice :message="error" type="error"/></div></section>
</template>
